services:
  - type: web
    name: exist-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT --workers 1 --timeout-keep-alive 120
    envVars:
      - key: TELEGRAM_TOKEN
        sync: false
      - key: OPENAI_API_KEY
        sync: false
      - key: GPTS_MODEL_ID
        sync: false
      - key: WEBHOOK_URL
        sync: false
      - key: PYTHONUNBUFFERED
        value: "1"
      - key: LOG_LEVEL
        value: "INFO"
      - key: PORT
        value: "10000" 