services:
  - type: web
    name: exist-search
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn main:app --bind 0.0.0.0:$PORT -k uvicorn.workers.UvicornWorker --timeout 120 --workers 2
    envVars:
      - key: PYTHON_VERSION
        value: 3.9
      - key: WEBHOOK_URL
        value: https://exist-search.onrender.com
      - key: TELEGRAM_TOKEN
        sync: false
      - key: OPENAI_API_KEY
        sync: false
      - key: GPTS_MODEL_ID
        sync: false 