services:
  - type: web
    name: exist-search
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn fastapi_bot:app --host=0.0.0.0 --port=$PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.9 